### PR TITLE
'spat.py' plug-in

### LINKED ISSUE #1: GNATStudio plugin
It could be handy to have a plug-in in GNATStudio so that the user can run the tool after a prove and see the information possibly interspersed with the actual source code.

Not clear yet, though, how the output should be displayed in the IDE.

### PR DESCRIPTION
**Pull request by Jellix**
* Adds `--raw` option for output mode.
* Adds the `spat.py' plug-in.

### CODE REVIEW

**Comment by yannickmoy** [comment]
hi @Jellix, I tried to use the GNAT Studio plugin with the Community 2020 version and current dev branch, and I'm not seeing any result, which is expected because the output of `run_spat` with option `--raw` is not in the format that GNAT Studio understands for compiler-like messages. Is that expected? How do you use the plugin currently? TIA

**Comment by Jellix** [comment]
> hi @Jellix, I tried to use the GNAT Studio plugin with the Community 2020 version and current dev branch, and I'm not seeing any result, which is expected because the output of `run_spat` with option `--raw` is not in the format that GNAT Studio understands for compiler-like messages. Is that expected? How do you use the plugin currently? TIA

I am not using the LocationParser. One reason being is that I sort of build a "histogram", so that different time intervals go into different categories, otherwise all output just ends up in one category and gets sorted by file name and location which is completely not what I wanted. Hence, the plug-in is parsing the output of run_spat itself and adding the found location to the Locations view. 

Roughly like: call GPS.Process with a regular expression that should match the VC_... output lines, handle the on_match callback from GPS.Process and extract the times from there (i.e. split by "/" separator). From there I build a preliminary list of file/location/time which then I sort by time and run GPS.Locations.add ().

So, yeah, it worked for me so far. You're running under Linux or Windows? Shouldn't matter, but so far I only tested under Linux, so maybe there is something system specific that I overlooked.

**Comment by Jellix** [comment]
Wait a moment, what do you mean by "current dev branch", there should only be 'master', the changes have already been merged, so just using HEAD should be fine. There is no "dev branch" ATM and the fixes_1.0 branch doesn't have the plugin at all, this is just meant for potential 1.0.x releases.

**Comment by Jellix** [comment]
Question: Do you have anything other than lower case letters and hyphens in the source filenames?

Right now, the regexp to find the file:line:column triplet is `"([a-z0-9-]+\.ad[bs]):(\d+):(\d+)"`, so if there are uppercase letters or something else, it won't match. That's something I should fix, anyway. Opened #45 for that.

**Comment by Jellix** [comment]
Ok, with the latest commit (see PR #46) the filename expression is now far more relaxed, @yannickmoy I strongly suspect you had underscores in your file names? That wasn't caught by the original expression, it should do now.

**Comment by yannickmoy** [comment]
ahaa indeed, I was trying to investigate but you were faster. It worked fine on a small example, but not in this code that indeed uses underscores in file names. thanks!

**Comment by yannickmoy** [comment]
and I confirm it works now, perfect!

**Pull request merged**
